SURFACE_WORKER_QUEUES_DMQ = ["queue1", "queue2", "queue3"]

SURFACE_WORKER_QUEUES_UQ = ["queue1"]

dash_tickers = ["NXPI", "EBAY", "AMAT", "ALGN", "NTES", "GOOGL", "NFLX", "AMZN", "FB", "FAST", "FISV",
           "ADSK", "ADP", "ORLY", "PCAR", "MU", "MSFT", "AMD", "EXPE"]


TICKERS_DISTRIBUTED = {"queue1": ["AAAU", "ABTX", "AMBO", "ARR", "ATEN", "ATHM", "ATLO", "AU", "AUB",
                                           "BBVA", "CARE", "CBMB", "CDOR", "CFBK", "CFFN", "CLRB", "CMCT", "COKE",
                                           "CTRA", "CYAD", "DGZ", "DHX", "DMTK", "EAF", "EHTH", "ENSV", "ESP",
                                           "EVGN", "FBNC", "FCFS", "FDX", "FFBC", "FFNW", "FNCB", "FNLC", "FRG",
                                           "FUMB", "FVCB", "GHC", "GNW", "HHT", "HST", "HUM", "IBND", "IBTH", "INS",
                                           "INT", "J", "JFK", "KEN", "LMNL", "METC", "MOBL", "MOV", "MRIN", "MRKR",
                                           "MRTN", "NCTY", "OPER", "OVB", "PBIP", "PCSB", "PEG", "PIH", "PKBK",
                                           "PMBC", "PNBK", "PRAH", "RBCAA", "RCS", "RM", "RTRX", "RVI", "SCHN",
                                           "SHW", "SI", "SLCA", "SMBK", "SP", "SRG", "STRM", "SVBI", "TESS", "THR",
                                           "TMDX", "TNXP", "TOWN", "TRMK", "TXMD", "UBA", "UJUL", "USI", "UTES",
                                           "VIR", "WBAI", "WTBA", "WVE", "XBI", "ZCMD", "WTBA"],
                "queue2": ["AVD", "BHLB", "CCRN", "CPTA", "ESBK", "ESRT", "EVBN", "GWGH", "INTG",
                                          "LC", "MATW", "NKSH", "OGS", "ONE", "PBIP", "PFHD", "PHGE", "PPIH", "PRK",
                                          "PVBC", "SGA", "SIEB", "UIHC", "XGN", "YJ", "AVD", "BHLB", "CCRN", "CPTA",
                                          "ESBK", "ESRT", "EVBN", "GWGH", "INTG", "LC", "MATW", "NKSH", "OGS",
                                          "ONE", "PBIP", "PFHD", "PHGE", "PPIH", "PRK", "PVBC", "SGA", "SIEB",
                                          "UIHC", "XGN", "YJ", "AVD", "BHLB", "CCRN", "CPTA", "ESBK", "ESRT",
                                          "EVBN", "GWGH", "INTG", "LC", "MATW", "NKSH", "OGS", "ONE", "PBIP",
                                          "PFHD", "PHGE", "PPIH", "PRK", "PVBC", "SGA", "SIEB", "UIHC", "XGN", "YJ",
                                          "AVD", "BHLB", "CCRN", "CPTA", "ESBK", "ESRT", "EVBN", "GWGH", "INTG",
                                          "LC", "MATW", "NKSH", "OGS", "ONE", "PBIP", "PFHD", "PHGE", "PPIH", "PRK",
                                          "PVBC", "SGA", "SIEB", "UIHC", "XGN", "YJ"],
                "queue3": ["AI", "ALCO", "ALNY", "ANIK", "ARKG", "ARTNA", "ATOS", "AVAL", "AXNX",
                                        "AZN", "BG", "BGSF", "BHB", "BJ", "BSAC", "CASS", "CENT", "CERS", "CGW",
                                        "CHCT", "CLIX", "CLX", "CMO", "CMP", "CNXN", "CONE", "CRBP", "CSTE", "CSTL",
                                        "CTLT", "CTT", "CTXR", "CUT", "CUTR", "CYBE", "DMO", "DRSK", "DXCM", "EME",
                                        "ERIE", "ESGR", "ETH", "FATE", "FBSS", "FEIM", "FIVN", "FLGB", "FR",
                                        "FTLB", "FTV", "GAN", "GCC", "GL", "GLU", "GRWG", "GURE", "HDB", "HTLD",
                                        "IBCP", "ICLK", "IDNA", "IMUX", "INDY", "ISBC", "IVC", "J", "JBSS", "JCO",
                                        "JJN", "JMP", "LEDS", "MKTX", "MMM", "MRVL", "NAPR", "NATH", "NCB", "NEWT",
                                        "NGE", "NTRA", "NUSI", "NVO", "NVR", "NXGN", "NYCB", "ORAN", "ORC",
                                        "PBE", "PCH", "PFBC", "PFBI", "PFGC", "PHUN", "PINC", "PRAA", "PSA", "RVSB",
                                        "RYB", "CYBE", "MRVL"]}


TICKERS_SYNCHED_AND_UQ = {"queue1": ["AAAU", "ABTX", "AMBO", "ARR", "ATEN", "ATHM", "ATLO", "AU", "AUB",
                                           "BBVA", "CARE", "CBMB", "CDOR", "CFBK", "CFFN", "CLRB", "CMCT", "COKE",
                                           "CTRA", "CYAD", "DGZ", "DHX", "DMTK", "EAF", "EHTH", "ENSV", "ESP",
                                           "EVGN", "FBNC", "FCFS", "FDX", "FFBC", "FFNW", "FNCB", "FNLC", "FRG",
                                           "FUMB", "FVCB", "GHC", "GNW", "HHT", "HST", "HUM", "IBND", "IBTH", "INS",
                                           "INT", "J", "JFK", "KEN", "LMNL", "METC", "MOBL", "MOV", "MRIN", "MRKR",
                                           "MRTN", "NCTY", "OPER", "OVB", "PBIP", "PCSB", "PEG", "PIH", "PKBK",
                                           "PMBC", "PNBK", "PRAH", "RBCAA", "RCS", "RM", "RTRX", "RVI", "SCHN",
                                           "SHW", "SI", "SLCA", "SMBK", "SP", "SRG", "STRM", "SVBI", "TESS", "THR",
                                           "TMDX", "TNXP", "TOWN", "TRMK", "TXMD", "UBA", "UJUL", "USI", "UTES",
                                           "VIR", "WBAI", "WTBA", "WVE", "XBI", "ZCMD", "WTBA", "AVD", "BHLB", "CCRN",
                                     "CPTA", "ESBK", "ESRT", "EVBN", "GWGH", "INTG",
                                          "LC", "MATW", "NKSH", "OGS", "ONE", "PBIP", "PFHD", "PHGE", "PPIH", "PRK",
                                          "PVBC", "SGA", "SIEB", "UIHC", "XGN", "YJ", "AVD", "BHLB", "CCRN", "CPTA",
                                          "ESBK", "ESRT", "EVBN", "GWGH", "INTG", "LC", "MATW", "NKSH", "OGS",
                                          "ONE", "PBIP", "PFHD", "PHGE", "PPIH", "PRK", "PVBC", "SGA", "SIEB",
                                          "UIHC", "XGN", "YJ", "AVD", "BHLB", "CCRN", "CPTA", "ESBK", "ESRT",
                                          "EVBN", "GWGH", "INTG", "LC", "MATW", "NKSH", "OGS", "ONE", "PBIP",
                                          "PFHD", "PHGE", "PPIH", "PRK", "PVBC", "SGA", "SIEB", "UIHC", "XGN", "YJ",
                                          "AVD", "BHLB", "CCRN", "CPTA", "ESBK", "ESRT", "EVBN", "GWGH", "INTG",
                                          "LC", "MATW", "NKSH", "OGS", "ONE", "PBIP", "PFHD", "PHGE", "PPIH", "PRK",
                                          "PVBC", "SGA", "SIEB", "UIHC", "XGN", "YJ", "AI", "ALCO", "ALNY", "ANIK", "ARKG", "ARTNA", "ATOS", "AVAL", "AXNX",
                                        "AZN", "BG", "BGSF", "BHB", "BJ", "BSAC", "CASS", "CENT", "CERS", "CGW",
                                        "CHCT", "CLIX", "CLX", "CMO", "CMP", "CNXN", "CONE", "CRBP", "CSTE", "CSTL",
                                        "CTLT", "CTT", "CTXR", "CUT", "CUTR", "CYBE", "DMO", "DRSK", "DXCM", "EME",
                                        "ERIE", "ESGR", "ETH", "FATE", "FB", "FBSS", "FEIM", "FIVN", "FLGB", "FR",
                                        "FTLB", "FTV", "GAN", "GCC", "GL", "GLU", "GRWG", "GURE", "HDB", "HTLD",
                                        "IBCP", "ICLK", "IDNA", "IMUX", "INDY", "ISBC", "IVC", "J", "JBSS", "JCO",
                                        "JJN", "JMP", "LEDS", "MKTX", "MMM", "MRVL", "NAPR", "NATH", "NCB", "NEWT",
                                        "NGE", "NTRA", "NUSI", "NVO", "NVR", "NXGN", "NXPI", "NYCB", "ORAN", "ORC",
                                        "PBE", "PCH", "PFBC", "PFBI", "PFGC", "PHUN", "PINC", "PRAA", "PSA", "RVSB",
                                        "RYB", "CYBE", "MRVL"]}